services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./storage:/app/storage
    environment:
      - DATABASE_URL=postgresql://sixpet:sixpet123@host.docker.internal:5434/sixpet_catalog
      - REDIS_URL=redis://host.docker.internal:6381/0
      - GROQ_API_KEYS=gsk_test
      - STORAGE_TYPE=filesystem
      - STORAGE_PATH=/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
